var list1 = [
  {
    id: 0,
    jobType: "B",
    jobNo: 0,
    customer: "Flip Farm",
    jobName: "Infeed Top Frame",
    qty: 10,
    process: "33066S",
    material: "L6P025NB27",
    materialIsReady: false,
    materialIsOrdered: false,
    mandrelIsReady: false,
    mandrelIsOrdered: false,
    isFinish: false,
    isEdit: false,
  },
  {
    id: 1,
    jobType: "E",
    jobNo: 1,
    customer: "Flip Farm",
    jobName: "Infeed Top Frame",
    qty: 10,
    process: "33066S",
    material: "L6P025NB27",
    materialIsReady: false,
    materialIsOrdered: false,
    mandrelIsReady: true,
    mandrelIsOrdered: false,
    isFinish: true,
    isEdit: false,
  },
  {
    id: 2,
    jobType: "A",
    jobNo: 2,
    customer: "ZWH",
    jobName: "S4076N76",
    qty: 60,
    process: "76076S",
    material: "L407616D",
    materialIsReady: true,
    materialIsOrdered: false,
    mandrelIsReady: false,
    mandrelIsOrdered: true,
    isFinish: true,
    isEdit: false,
  },
  {
    id: 3,
    jobType: "A",
    jobNo: 3,
    customer: "IMG001",
    jobName: "Test Frame",
    qty: 40,
    process: "33066S",
    material: "L6P025NB27",
    materialIsReady: false,
    materialIsOrdered: false,
    mandrelIsReady: false,
    mandrelIsOrdered: false,
    isFinish: false,
    isEdit: false,
  },
  {
    id: 4,
    jobType: "A",
    jobNo: 4,
    customer: "CHEN001",
    jobName: "Outfeed Top Frame",
    qty: 10,
    process: "33066S",
    material: "L6P025NB27",
    materialIsReady: false,
    materialIsOrdered: false,
    mandrelIsReady: false,
    mandrelIsOrdered: false,
    isFinish: false,
    isEdit: false,
  },
  {
    id: 5,
    jobType: "A",
    jobNo: 5,
    customer: "STAY002",
    jobName: "Handle",
    qty: 10,
    process: "44044S",
    material: "L6P025NB27",
    materialIsReady: false,
    materialIsOrdered: true,
    mandrelIsReady: false,
    mandrelIsOrdered: false,
    isFinish: false,
    isEdit: false,
  },
  {
    id: 6,
    jobType: "A",
    jobNo: 6,
    customer: "EHMO002",
    jobName: "Rolling Cages",
    qty: 10,
    process: "33066S",
    material: "L6P025NB27",
    materialIsReady: false,
    materialIsOrdered: false,
    mandrelIsReady: true,
    mandrelIsOrdered: false,
    isFinish: false,
    isEdit: false,
  },
  {
    id: 7,
    jobType: "A",
    jobNo: 7,
    customer: "Test 7",
    jobName: "Infeed Top Frame",
    qty: 10,
    process: "33066S",
    material: "L6P025NB27",
    materialIsReady: false,
    materialIsOrdered: false,
    mandrelIsReady: false,
    mandrelIsOrdered: false,
    isFinish: false,
    isEdit: false,
  },
  {
    id: 8,
    jobType: "B",
    jobNo: 8,
    customer: "Test 8",
    jobName: "Infeed Top Frame",
    qty: 10,
    process: "33066S",
    material: "L6P025NB27",
    materialIsReady: false,
    materialIsOrdered: false,
    mandrelIsReady: false,
    mandrelIsOrdered: false,
    isFinish: false,
    isEdit: false,
  },
  {
    id: 9,
    jobType: "A",
    jobNo: 0,
    customer: "HAHA10",
    jobName: "What bending",
    qty: 10,
    process: "33066S",
    material: "L6P025NB27",
    materialIsReady: true,
    materialIsOrdered: false,
    mandrelIsReady: false,
    mandrelIsOrdered: false,
    isFinish: false,
    isEdit: false,
  },
  {
    id: 10,
    jobType: "B",
    jobNo: 0,
    customer: "Flip Farm",
    jobName: "Infeed Top Frame",
    qty: 10,
    process: "33066S",
    material: "L6P025NB27",
    materialIsReady: false,
    materialIsOrdered: false,
    mandrelIsReady: false,
    mandrelIsOrdered: false,
    isFinish: false,
    isEdit: false,
  },
  {
    id: 11,
    jobType: "E",
    jobNo: 1,
    customer: "Flip Farm",
    jobName: "Infeed Top Frame",
    qty: 10,
    process: "33066S",
    material: "L6P025NB27",
    materialIsReady: false,
    materialIsOrdered: false,
    mandrelIsReady: true,
    mandrelIsOrdered: false,
    isFinish: true,
    isEdit: false,
  },
  {
    id: 12,
    jobType: "E",
    jobNo: 2,
    customer: "ZWH",
    jobName: "S4076N76",
    qty: 60,
    process: "76076S",
    material: "L407616D",
    materialIsReady: true,
    materialIsOrdered: false,
    mandrelIsReady: false,
    mandrelIsOrdered: true,
    isFinish: true,
    isEdit: false,
  },
  {
    id: 13,
    jobType: "B",
    jobNo: 3,
    customer: "IMG001",
    jobName: "Test Frame",
    qty: 40,
    process: "33066S",
    material: "L6P025NB27",
    materialIsReady: false,
    materialIsOrdered: false,
    mandrelIsReady: false,
    mandrelIsOrdered: false,
    isFinish: false,
    isEdit: false,
  },
  {
    id: 14,
    jobType: "B",
    jobNo: 4,
    customer: "CHEN001",
    jobName: "Outfeed Top Frame",
    qty: 10,
    process: "33066S",
    material: "L6P025NB27",
    materialIsReady: false,
    materialIsOrdered: false,
    mandrelIsReady: false,
    mandrelIsOrdered: false,
    isFinish: false,
    isEdit: false,
  },
  {
    id: 15,
    jobType: "E",
    jobNo: 5,
    customer: "STAY002",
    jobName: "PUSH BEND",
    qty: 10,
    process: "44044S",
    material: "L6P025NB27",
    materialIsReady: false,
    materialIsOrdered: true,
    mandrelIsReady: false,
    mandrelIsOrdered: false,
    isFinish: false,
    isEdit: false,
  },
  {
    id: 16,
    jobType: "A",
    jobNo: 6,
    customer: "EHMO002",
    jobName: "Rolling Cages",
    qty: 10,
    process: "33066S",
    material: "L6P025NB27",
    materialIsReady: false,
    materialIsOrdered: false,
    mandrelIsReady: true,
    mandrelIsOrdered: false,
    isFinish: false,
    isEdit: false,
  },
  {
    id: 17,
    jobType: "A",
    jobNo: 7,
    customer: "Test 7",
    jobName: "Infeed Top Frame",
    qty: 10,
    process: "33066S",
    material: "L6P025NB27",
    materialIsReady: false,
    materialIsOrdered: false,
    mandrelIsReady: false,
    mandrelIsOrdered: false,
    isFinish: false,
    isEdit: false,
  },
  {
    id: 18,
    jobType: "B",
    jobNo: 8,
    customer: "Test 8",
    jobName: "Infeed Top Frame",
    qty: 10,
    process: "33066S",
    material: "L6P025NB27",
    materialIsReady: false,
    materialIsOrdered: false,
    mandrelIsReady: false,
    mandrelIsOrdered: false,
    isFinish: false,
    isEdit: false,
  },
  {
    id: 19,
    jobType: "E",
    jobNo: 0,
    customer: "HAHA10",
    jobName: "Rolling",
    qty: 10,
    process: "33066S",
    material: "L6P025NB27",
    materialIsReady: true,
    materialIsOrdered: false,
    mandrelIsReady: false,
    mandrelIsOrdered: false,
    isFinish: false,
    isEdit: false,
  },
];
const mysql = require('mysql')

const db = mysql.createPool({
  host:'13.211.232.130',
  port:3306,
  user:'root',
  password:'root',
  database:'Autobend'
})

// module.exports={db}


list1.forEach(element => {

  let {jobType,jobNo,customer, jobName,qty,process,material,materialIsReady,materialIsOrdered,mandrelIsReady,mandrelIsOrdered,isFinish,isEdit} = element;
  db.query(`INSERT INTO Autobend_jobs VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,? )`,[0,jobType,jobNo,customer, jobName,qty,process,material,materialIsReady,materialIsOrdered,mandrelIsReady,mandrelIsOrdered,isFinish,isEdit],(err,data)=>{
    if (err) return console.log(err)
    
    console.log(data)
  
  } )
});

  // db.query(`INSERT INTO Autobend_jobs VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,? )`,[0,"C",0,"Flip Farm","Infeed Top Frame",10,"33066S","L6P025NB27",0,0,0,0,0,0],(err,data)=>{
//   if (err) return console.log(err)
  
//   console.log(data)

// } )


// db.query('INSERT INTO Autobend_jobs VALUES (2,"B",0,"Flip Farm","Infeed Top Frame",10,"33066S","L6P025NB27",0,0,0,0,0,0)',(err,data)=>{
//   if (err) return console.log(err)
  
//   console.log(data)

// } )

// db.query('SELECT * FROM Autobend_jobs',(err,data)=>{
//   if (err) return console.log(err)

//   console.log(data)
// })

